repos:
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        name: Format Package

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.2
    hooks:
      - id: flake8
        name: Lint Package

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.1
    hooks:
      - id: seed-isort-config
        name: Propogate Third-Party Packages

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        name: Sort Package Imports

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
      - id: mypy
        name: Typecheck Package
