name: Test Package
on: [push, pull_request]
jobs:
  test:
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: [3.6, 3.7]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e .[test] --upgrade
      - name: Run Tests
        run: |
          pytest
  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Use Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Coverage Reporters
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade coverage codacy-coverage codecov
          python -m pip install -e .[test] --upgrade
      - name: Run Tests
        run: |
          pytest
      - name: Build Coverage Report
        run: |
          coverage xml -o coverage.xml
      - name: Publish Coverage
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          python-codacy-coverage -r coverage.xml
          codecov
